send watch logs to /dev/null

diff --git a/enforce/.github/workflows/build-test-release.yml b/enforce/.github/workflows/build-test-release.yml
--- a/enforce/.github/workflows/build-test-release.yml
+++ b/enforce/.github/workflows/build-test-release.yml
@@ -578,7 +578,9 @@ jobs:
         env:
           ARGO_TOKEN: ${{ steps.get-argo-token.outputs.argo-token }}
         if: always()
-        run: until argo watch ${{ steps.run-tests.outputs.workflow-name }} -n workflows; do echo "argo watch ended with failure $?. Trying again"; sleep 60; done
+        run: |
+          until argo watch ${{ steps.run-tests.outputs.workflow-name }} -n workflows > /dev/null; do echo "argo watch ended with failure $?. Trying again"; sleep 60; done
+          argo watch ${{ steps.run-tests.outputs.workflow-name }} -n workflows
       - name: pull artifacts from s3 bucket
         if: always()
         run: |
@@ -685,7 +687,9 @@ jobs:
         if: always()
         env:
           ARGO_TOKEN: ${{ steps.get-argo-token.outputs.argo-token }}
-        run: until argo watch ${{ steps.run-tests.outputs.workflow-name }} -n workflows; do echo "argo watch ended with failure $?. Trying again"; sleep 60; done
+        run: |
+          until argo watch ${{ steps.run-tests.outputs.workflow-name }} -n workflows > /dev/null; do echo "argo watch ended with failure $?. Trying again"; sleep 60; done
+          argo watch ${{ steps.run-tests.outputs.workflow-name }} -n workflows
       - name: pull artifacts from s3 bucket
         if: always()
         run: |
@@ -792,7 +796,9 @@ jobs:
         if: always()
         env:
           ARGO_TOKEN: ${{ steps.get-argo-token.outputs.argo-token }}
-        run: until argo watch ${{ steps.run-tests.outputs.workflow-name }} -n workflows; do echo "argo watch ended with failure $?. Trying again"; sleep 60; done
+        run: |
+          until argo watch ${{ steps.run-tests.outputs.workflow-name }} -n workflows > /dev/null; do echo "argo watch ended with failure $?. Trying again"; sleep 60; done
+          argo watch ${{ steps.run-tests.outputs.workflow-name }} -n workflows
       - name: pull artifacts from s3 bucket
         if: always()
         run: |
